---
- hosts: localhost
  gather_facts: False
  connection: local

  tasks:
  - name: Perform a live-paste from Quip Source to Quip Destinations
    quip_paste:
      token: "{{ quip_token }}" 
      base_api_url: 'https://platform.quip.com'
      source_url: 'https://<sub-domain>.quip.com/<document-id>/<document-name>'
      source_section_id: '<source-data-id>'
      destination_urls:
        - https://<sub-domain>.quip.com/<document-id>/<document-name>
        - redhat.quip.com/<doc-id>/<doc-name>
        - not-working-example.quip.com/ZZZZZZZZZZ/NOT-REAL-DOC
      target_header: "Welcome to Quip"
      prepend: False

  - name: Use quip_update_cell to update the cell text in a Quip table
    quip_update_cell:
      token: "{{ quip_token }}" 
      find: 'Number'
      replace: 'Contact'
      markdown: 'bold'
      quip_urls:
        - <sub-domain>.quip.com/<document-id>/<document-name>
        - not.a.working.example.com/EXPECTEDFAIL/missing-quip-dotcom
...
